controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint
  - name: fake_left_arm_controller
    joints:
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
  - name: fake_right_hand_controller
    joints:
      - right_HandFingerOneKnuckleOneJoint
      - right_HandFingerOneKnuckleTwoJoint
      - right_HandFingerOneKnuckleThreeJoint
      - right_HandFingerThreeKnuckleTwoJoint
      - right_HandFingerThreeKnuckleThreeJoint
      - right_HandFingerTwoKnuckleOneJoint
      - right_HandFingerTwoKnuckleTwoJoint
      - right_HandFingerTwoKnuckleThreeJoint
  - name: fake_left_hand_controller
    joints:
      - left_HandFingerOneKnuckleOneJoint
      - left_HandFingerOneKnuckleTwoJoint
      - left_HandFingerOneKnuckleThreeJoint
      - left_HandFingerThreeKnuckleTwoJoint
      - left_HandFingerThreeKnuckleThreeJoint
      - left_HandFingerTwoKnuckleOneJoint
      - left_HandFingerTwoKnuckleTwoJoint
      - left_HandFingerTwoKnuckleThreeJoint